### ISSUE TITLE
Doubts before integrating

### ISSUE THREAD

**Issue by Curbe8** [transistorsoft/cordova-background-geolocation-firebase#10]
## Your Environment

A description of the environment is not necessary for this issue.
Just clarify that I use Firebase Realtime Database and Ionic 3.

# Description

This problem was opened with the intention of clearing doubts. Is it possible to integrate with Real Time Database or only with Cloud Firestore?
Is the integration of cordova-background-geolocation necessary for the use of this add-on or only with the integration of Cordova-background-geolocation-firebase is enough?

Thank you!

**Comment by christocracy** [comment]
>with Real Time Database or only with Cloud Firestore?

Firestore only.

>Is the integration of cordova-background-geolocation necessary for the use of this add-o

You must first implement `cordova-background-geolocation`.  This plugin is *an adapter for* `cordova-background-geolocation`

**Comment by Curbe8** [comment]
> Firestore only.
Something in mind to migrate data from "Cloud Firestore" to "Firebase Realtime Database" in real time?

**Comment by Curbe8** [comment]
> Firestore only.

Something in mind to migrate data from "Cloud Firestore" to "Firebase Realtime Database" in real time?

**Comment by christocracy** [comment]
Could you do this with [Cloud Functions](https://firebase.google.com/docs/functions)?

**Comment by Curbe8** [comment]
I had no idea that that was possible.
I will have to investigate, thank you very much!

**Comment by christocracy** [comment]
They’re easy and the cost is negligible since it doesn’t involve reaching outside with a network request.

**Comment by Curbe8** [comment]
If it is to imagine.
The api key mentioned is the one generated for cordova-background-geolocation?

**Comment by christocracy** [comment]
>The api key mentioned is the one generated for cordova-background-geolocation?

No.  This firebase adapter requires purchasing its [own license key](https://www.transistorsoft.com/shop/products/background-geolocation-firebase)

**Comment by Curbe8** [comment]
Does the version of `GOOGLE_API_VERSION` have to be necessarily `["16.+"]` or can it be earlier?

**Comment by christocracy** [comment]
You should use the latest available play-services.

**Comment by Curbe8** [comment]
I agree but the use of Firebase does not allow me to use that version, it generates conflicts.

**Comment by christocracy** [comment]
You must tell Firebase to align to the correct version.  Cordova is horrible for aligning android dependencies.  React Native and Flutter are much better at this.  Post your `platforms/android/project.properties`.

**Comment by christocracy** [comment]
Play Services is like an extension to the OS.  You *never* fall back to an older version "just because it works".

**Comment by Curbe8** [comment]
```target=android-27
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-background-fetch/FixBeep-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:16.0.0
cordova.system.library.2=com.android.support:appcompat-v7:27.+
cordova.system.library.3=com.squareup.okhttp3:okhttp:3.12.+
cordova.system.library.4=org.greenrobot:eventbus:3.0.0
cordova.system.library.5=com.intentfilter:android-permissions:0.1.8
cordova.system.library.6=org.slf4j:slf4j-api:1.7.25
cordova.system.library.7=com.github.tony19:logback-android:1.3.0-2
cordova.gradle.include.2=cordova-background-geolocation/FixBeep-build.gradle
cordova.system.library.8=com.facebook.android:facebook-android-sdk:4.38.1
cordova.gradle.include.3=cordova-plugin-googlemaps/FixBeep-tbxml-android.gradle
cordova.system.library.9=com.google.android.gms:play-services-maps:16.0.0
cordova.system.library.10=com.google.android.gms:play-services-location:16.0.0
cordova.system.library.11=com.android.support:support-core-utils:27.+
cordova.system.library.12=com.android.support:support-annotations:27.+
cordova.system.library.13=com.squareup.okhttp3:okhttp:3.+
cordova.system.library.14=com.google.firebase:firebase-core:16.+
cordova.system.library.15=com.google.firebase:firebase-messaging:16.+
cordova.gradle.include.4=cordova-plugin-fcm-with-dependecy-updated/FixBeep-FCMPlugin.gradle
```

In fact right now there is a new version of google [Play Services Location](https://mvnrepository.com/artifact/com.google.android.gms/play-services-location/17.0.0)

**Comment by christocracy** [comment]
Your problem is with [cordova-plugin-fcm-with-dependency-updated](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/master/src/android/FCMPlugin.gradle#L17).  This file was committed on Dec 12, 2018.  This plugin is no longer current.

```
compile 'com.google.firebase:firebase-core:10.+'
```

Browse https://maven.google.com to see a list of all google dependencies:
![](https://dl.dropbox.com/s/a418859tfk9blqh/Screenshot%202019-08-15%2010.15.26.png?dl=1)

**Comment by Curbe8** [comment]
> ```
> compile 'com.google.firebase:firebase-core:10.+'
> ```

I had no result with this change

**Comment by Curbe8** [comment]
![image](https://user-images.githubusercontent.com/31408207/63130400-ae2ea880-bf90-11e9-8628-2614a28863ac.png)

**Comment by Curbe8** [comment]
Any recommendation? @christocracy

**Comment by christocracy** [comment]
Your [`cordova-plugin-fcm-with-dependency-updated`](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/master/src/android/FCMPlugin.gradle#L17) is no longer current, using `firebase-core:10.+`.  Latest `firebase-core` is `17.1.0`.

`cordova-plugin-fcm` is one of the *worst* plugins.  It hasn't received a commit [since Jan 20, 2018](https://www.dropbox.com/s/ksvoggojy9csfng/Screenshot%202019-08-22%2008.56.10.png?dl=0) with **396** open issues.  Get rid of that plugin and find an alternative or clone it and update the dependencies as required or search [its network](https://github.com/fechanique/cordova-plugin-fcm/network) to find a fork of someone who already has.

You can add any Git repo url to `cordova plugin add <any-git-url>`

![](https://dl.dropbox.com/s/s8qbtbgfgqdgi3x/Screenshot%202019-08-22%2009.00.31.png?dl=1)
